language: minimal

node_js:
  - node

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.62.1/hugo_extended_0.62.1_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.62.1_Linux-64bit.deb
  - rm hugo_extended_0.62.1_Linux-64bit.deb
  - npm install babel-cli@6 babel-preset-react-app@3

script:
  - cd hugo
  - npx babel assets/js-src/ --out-dir assets/js/ --presets react-app/prod  # Transform jsx to js.
  - hugo  # Generate the static site.

after_success:
  - cd ../..
  - git clone --branch deploy https://${GH_TOKEN}@github.com/dbieber/davidbieber.com.git davidbieber.com-deploy
  - rsync -av davidbieber.com/ davidbieber.com-deploy/ --delete --exclude=.gitignore --exclude=.git

  - cd davidbieber.com-deploy
  - git config user.email "david810@gmail.com"
  - git config user.name "David Bieber"

  - git add .
  - git commit -m '[skip travis] Automatic commit by Travis CI'
  - git push origin deploy

env:
  global:
    secure: TE4QJTx/fg0zqTro+DI8pVjL80A/DjGO4I+/kj/SVZu2ROpGuVJ5TTV9VPAfF2V/Ye2cgyVnv1p4yYKNRfOGx1KfI6MIFa6qMJR7f2vIW2X8mRwmTIs2MhA+FA+54vXdPaHitPIG6w11X2yT6kTJI6kTjtuh4Pn5MmyUQwwNLCa7PCgEpFL/B5AsEPYTmLvCuxQPueqasI2WtdX/7Jm2LSGrFiTQY26gtqgbsHvRiv+AwwQea5PGfN1uPbS+6fzUh09kM58h5vzmcYweehnjsJQhBvZrK1hBIkRVGOhRVE6ALUnDQh+/QbnBJU/uKkSUoBeI624tDhzge5wukUqwXqQInrdBdEv2EH0LGJRb+UhHV0qv2ehZm0N4YRdSDB0W/nDhfAUZ5F/2+i2hpfowGK2zjA6l2gSi+jdRsRCX9yMRS1qoGNQJ8JwFfqCeqnG4Tqm8gO6WjqYtdHk1wLqssAZW66+jYct1HFDuflP3uEPXOR/QMN/IDJZVOD57E32DHKvOg0SKvHa8NWaNuai50v/qcT9vvonaoOBhI56QpaXT+5LteREHA31cIHPt0fWERx6ccBMExj4fNJwnWCeVayEvP+BaZU+VoEGZ/+s/7k4mF+ak87VHc8lPJ3LAk6oUsXTwYIcgqRmLexvvHodjBlXdAjRPtjHh8QV18Dsx0qo=

branches:
  only:
  - master
