---
- hosts: www

  tasks:
  - name: install git
    apt:
      name: git
      state: present
    become: true

  - name: install pip
    apt:
      name: python3-pip
      state: present
    become: true

  - name: install virtualenv
    pip:
      name: virtualenv
    become: true

  - name: setup davidbieber.com
    git: repo=https://github.com/dbieber/davidbieber.com dest=/home/dbieber/davidbieber.com version=deploy force=true
    become: true

  - name: install python dependencies
    pip:
      requirements: /home/dbieber/davidbieber.com/requirements.txt
      virtualenv: /home/dbieber/davidbieber.com/virtualenv
    become: true

  - name: get files ready to serve
    shell: cp -r hugo/public/* default/
    become: true
    args:
      chdir: /home/dbieber/davidbieber.com

  - name: start server app.py
    shell: nohup ./virtualenv/bin/python -m app --port 443 --redirect &
    become: true
    args:
      chdir: /home/dbieber/davidbieber.com

  # - name: download certbot
  #   get_url: >
  #     url=https://dl.eff.org/certbot-auto
  #     dest=/home/dbieber/certbot-auto
