name: build-website
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      # Install Hugo.
      - run: curl -LO https://github.com/gohugoio/hugo/releases/download/v0.62.1/hugo_extended_0.62.1_Linux-64bit.deb
      - run: sudo dpkg -i hugo_extended_0.62.1_Linux-64bit.deb
      - run: rm hugo_extended_0.62.1_Linux-64bit.deb
      # Install babel with React presets.
      - run: npm install
      - run: cat package.json

      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash

      - uses: actions/checkout@v2
        with:
          ref: deploy
          path: davidbieber.com-deploy

      - name: Push to deploy branch
        run: ./.github/scripts/deploy.sh
        shell: bash
