name: publish-roam-snippets
on:
  repository_dispatch:
    types: snippet-update

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      SNIPPET_UID: ${{ github.event.client_payload.uid }}
      SNIPPET_TITLE: ${{ github.event.client_payload.title }}
      SNIPPET_DATE: ${{ github.event.client_payload.date }}
      SNIPPET_CONTENT: ${{ github.event.client_payload.content }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: davidbieber.com-main
      - run: python ./davidbieber.com-main/.github/scripts/publish.py
