name: publish-roam-snippets
on:
  repository_dispatch:
    types: snippet-update

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      SNIPPET_CONTENT: ${{ github.event.client_payload.content }}
    steps:
      - run: |
          pwd
          ls
          echo "Hello ${{ github.event.client_payload.uid }}!"
          echo "Hello ${{ github.event.client_payload.title }}!"
          echo "Hello ${{ github.event.client_payload.date }}!"
          echo "Content: $SNIPPET_CONTENT!"
